# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.

image: python:3.5.1
pipelines:
  default:
  #  - step:
  #      script:

  production:
    - step:
        script:
          - python --version
          - apt-get update # required to install zip
          - pip install boto3==1.3.0 # required for beanstalk_deploy.py
          - zip -r /tmp/artifact.zip * .ebextensions/* # package up the application for deployment
          - export APPLICATION_ENVIRONMENT=Sample-env
          - python beanstalk_deploy.py # run the deployment script
